"""Alembic 迁移脚本模板"""
"Initial migration"

Revision ID: e9d55b6bd367
Revises: 
Create Date: 2026-01-08 12:58:27.744959+08:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic
revision: str = 'e9d55b6bd367'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gifts',
    sa.Column('gift_id', sa.String(length=32), nullable=False, comment='礼品ID'),
    sa.Column('gift_name', sa.String(length=200), nullable=False, comment='礼品名称'),
    sa.Column('gift_category', sa.String(length=50), nullable=False, comment='礼品分类'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='单价(元)'),
    sa.Column('stock_quantity', sa.Integer(), nullable=True, comment='库存数量'),
    sa.Column('description', sa.Text(), nullable=True, comment='礼品描述'),
    sa.Column('status', mysql.ENUM('ACTIVE', 'INACTIVE'), nullable=True, comment='状态'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('gift_id')
    )
    op.create_table('system_configs',
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='配置项键名'),
    sa.Column('config_value', sa.Text(), nullable=False, comment='配置项值(JSON字符串)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='配置项描述'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('config_key')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=32), nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录账号'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='用户姓名'),
    sa.Column('role', mysql.ENUM('CUSTOMER_MANAGER', 'OPERATIONS', 'APPROVER', 'MANAGER'), nullable=False, comment='角色'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='所属部门'),
    sa.Column('status', mysql.ENUM('ACTIVE', 'INACTIVE', 'LOCKED'), nullable=False, comment='用户状态'),
    sa.Column('last_login_time', sa.String(length=50), nullable=True, comment='最后登录时间'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('carousels',
    sa.Column('carousel_id', sa.String(length=32), nullable=False, comment='轮播图ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='图片URL'),
    sa.Column('link_url', sa.String(length=500), nullable=True, comment='跳转链接'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序序号(数字越小越靠前)'),
    sa.Column('status', mysql.ENUM('ACTIVE', 'INACTIVE'), nullable=True, comment='状态'),
    sa.Column('create_by', sa.String(length=32), nullable=False, comment='创建人(用户ID)'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['create_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('carousel_id')
    )
    op.create_table('customer_visits',
    sa.Column('visit_id', sa.String(length=32), nullable=False, comment='拜访记录ID'),
    sa.Column('customer_id', sa.String(length=50), nullable=False, comment='客户ID'),
    sa.Column('company_name', sa.String(length=200), nullable=False, comment='企业名称'),
    sa.Column('planned_date', sa.Date(), nullable=False, comment='计划拜访日期'),
    sa.Column('actual_date', sa.Date(), nullable=True, comment='实际拜访日期'),
    sa.Column('visit_method', mysql.ENUM('ON_SITE', 'PHONE', 'VIDEO', 'EMAIL', 'OTHER'), nullable=False, comment='拜访方式'),
    sa.Column('interested_products', sa.JSON(), nullable=True, comment='意向理财产品列表(JSON数组)'),
    sa.Column('participants', sa.JSON(), nullable=True, comment='参与人员列表(JSON数组,存储用户ID)'),
    sa.Column('status', mysql.ENUM('NEW', 'IN_PROGRESS', 'SUCCESS', 'FAILED', 'CANCELLED'), nullable=False, comment='拜访状态'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注信息'),
    sa.Column('create_by', sa.String(length=32), nullable=False, comment='创建人(用户ID)'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['create_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('visit_id')
    )
    op.create_table('gift_requisitions',
    sa.Column('requisition_id', sa.String(length=32), nullable=False, comment='申请单ID'),
    sa.Column('applicant', sa.String(length=32), nullable=False, comment='申请人(用户ID)'),
    sa.Column('recipient', sa.String(length=32), nullable=False, comment='领用人(用户ID)'),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='总金额(元)'),
    sa.Column('planned_date', sa.Date(), nullable=False, comment='计划领用日期'),
    sa.Column('purpose_type', mysql.ENUM('CUSTOMER_VISIT', 'HOLIDAY', 'MARKETING', 'OTHER'), nullable=False, comment='目的类型'),
    sa.Column('related_visit_id', sa.String(length=32), nullable=True, comment='关联客户拜访记录ID'),
    sa.Column('approval_status', mysql.ENUM('PENDING', 'APPROVED', 'REJECTED'), nullable=False, comment='审批状态'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='驳回原因'),
    sa.Column('approver', sa.String(length=32), nullable=True, comment='审批人(用户ID)'),
    sa.Column('approval_time', sa.String(length=50), nullable=True, comment='审批时间'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['applicant'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['approver'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('requisition_id')
    )
    op.create_table('news',
    sa.Column('news_id', sa.String(length=32), nullable=False, comment='新闻ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='新闻标题'),
    sa.Column('summary', sa.String(length=500), nullable=False, comment='新闻摘要'),
    sa.Column('content', sa.Text(), nullable=False, comment='新闻正文内容'),
    sa.Column('publish_time', sa.String(length=50), nullable=True, comment='发布时间'),
    sa.Column('status', mysql.ENUM('DRAFT', 'PUBLISHED', 'WITHDRAWN'), nullable=True, comment='状态'),
    sa.Column('create_by', sa.String(length=32), nullable=False, comment='创建人(用户ID)'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['create_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('news_id')
    )
    op.create_table('gift_requisition_items',
    sa.Column('item_id', sa.String(length=32), nullable=False, comment='明细项ID'),
    sa.Column('requisition_id', sa.String(length=32), nullable=False, comment='申请单ID'),
    sa.Column('gift_id', sa.String(length=32), nullable=False, comment='礼品ID'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='单价(元)'),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False, comment='小计(元)'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.gift_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requisition_id'], ['gift_requisitions.requisition_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gift_requisition_items')
    op.drop_table('news')
    op.drop_table('gift_requisitions')
    op.drop_table('customer_visits')
    op.drop_table('carousels')
    op.drop_table('users')
    op.drop_table('system_configs')
    op.drop_table('gifts')
    # ### end Alembic commands ###
